date: дата
productName: Наименование продукта
url: url
price: цена
presence: наличие

Warlock is listening...: Колдун слушает...
What do you want me to do?: Что ты желаешь, чтобы я сделал?
Do you want something more?: Ты хотел бы что-то ещё?
Gooood...: Хорошоооо...
Call me, any time to make your wish come true...: Визывай, когда что-нибудь пожелаешь...

For what product?: Для какого продукта?
Please, enter the product name!: Пожалуйста, укажите название продукта
Please, enter the product URL!: Пожалуйста, укажите URL продукта
Please, enter the name of the product you want to REMOVE!: Пожалуйста, введите название продукта, который вы хотите УДАЛИТЬ!
Please, enter \'yes\' or \'no\', or \'y\' or \'n\': Пожалуйста, введите с клавиатуры \'yes\' или \'no\', или \'y\' или \'n\'

Running the tracking...: Запускается трекинг...
this is the processor to parse the data from web-sites...: это процессор для получения данных с веб-сайтов...
Retrieving ... : Получение ...
Something went wrong, or there is no product status on the page.: Что-то пошло не так, или на странице нет статуса продукта.

Please type the language short code [ua, ru, en]: Пожалуйста напишите сокращенный индекс языка [ua, ru, en]
Please, enter the currency short name (usd, eur, bps): Пожалуйста укажите сокращенный индекс валюты (usd, eur, bps)
Price changes for product \': Изменения цены продукта \'
\' for last 5 days: \' за прошедшие 5 дней
There is no Price History for this product yet!: Для этого продукта ещё нет истории изменения цены!
DEMO History diagram (for single data set): DEMO диаграма истории изменений (для одного набора данных)
DEMO Multi History diagram (for multi data set): DEMO диаграма истории изменений (для нескольких графиков)

Log file removed successfuly.: Лог файл успешно удалён.
Catalogue contents: Каталог содержит
Chart legend: Линии графика