services:
  python:
    build: ./docker
    container_name: python_service
    volumes:
      - .:/app
    ports:
      - 80:80
    tty: true
    stdin_open: true

  python-tests:
    build: ./docker
    container_name: python_tests_service
    volumes:
      - .:/app
    tty: true
