date: дата
productName: Найменування продукту
url: url
price: ціна
presence: наявність

Warlock is listening...: Чаклун слухає...
What do you want me to do?: Що ти бажаєш, щоб я зробив?
Do you want something more?: Ти хотів би щось іще?
Gooood...: Гарааазд...
Call me, any time to make your wish come true...: Викликай, коли щось побажаєш...

For what product?: Для якого продукту?
Please, enter the product name!: Будь ласка, вкажіть назву продукту
Please, enter the product URL!: Будь ласка, вкажіть URL продукту
Please, enter the name of the product you want to REMOVE!: Будь ласка, введіть назву продукту, який ви хочете ВИДАЛИТИ!
Please, enter \'yes\' or \'no\', or \'y\' or \'n\': Будь ласка, введіть з клавіатури ''yes'' або ''no'', або ''y'' або ''n''

Running the tracking...: Запускається трекінг...
this is the processor to parse the data from web-sites...: це процесор для отримання даних з веб-сайтів...
Retrieving ...: Отримання ...
Something went wrong, or there is no product status on the page.: Щось пішло не так, або на сторінці немає статусу продукту.

Please type the language short code [ua, ru, en]: Будь ласка напишіть скорочений індекс мови [ua, ru, en]
Please, enter the currency short name (usd, eur, bps): Будь ласка вкажіть скорочений індекс валюти (usd, eur, bps)
Price changes for product \': Зміни ціни продукту \'
\' for last 5 days: \' за минулі 5 днів
There is no Price History for this product yet!: Для цього продукту ще немає історії змін ціни!
DEMO History diagram (for single data set): DEMO діаграма історії змін (для одного набора даних)
DEMO Multi History diagram (for multi data set): DEMO діаграма історії змін (для кількох графіків)

Log file removed successfuly.: Лог файл успішно видалено.
Catalogue contents: Каталог містить
Chart legend: Лінії графіка