name: Trivy Security Scan

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    name: Scan Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Local Docker Image
        run: |
          docker build -t warlock_python-python:latest ./docker

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'warlock_python-python:latest'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1' # Пайплайн впаде, якщо знайде вразливості
          severity: 'CRITICAL,HIGH'
